### PR TITLE
3D Reconstruction Module (in progress PR)

### PR DESCRIPTION
**Pull request by adamchang2000**
Requires downloading and installing my version of Open3D.
git clone https://github.com/adamchang2000/Open3D
mkdir build && cd build
cmake -G "Visual Studio 14 2015 Win64" ..
cmake --build . --config Release --parallel 8 --target install

The Open3D cmake has an issue, the libraries don't have paths so you may have to insert them in yourself. I'll look into fixing the cmakelists.

### CODE REVIEW

**Comment by adamchang2000** [comment]
The Open3D cmake issue has been fixed.
Adding Open3D as a dependency should be as seamless as adding all the other dependencies.

**Comment by fcr3** [comment]
Verified on MSI Windows 10 laptop. Also need to add instructions for recursive cloning on Open3D. Built from Adam's 3drecon-merge branch. The CMAKELists.txt was defaulting to Azure sdk instead of librealsense2 sdk.

**Comment by adamchang2000** [comment]
update: when installing open3d dependency, need to use this command:
git clone https://github.com/adamchang2000/Open3D --recursive
to install sub-dependencies.
Additionally, currently requires python to install open3d, will change the cmakelist to not require python

**Comment by fcr3** [comment]
@adamchang2000 , will you also work on the fast install, or is that something for me to do?

**Comment by adamchang2000** [comment]
I tidied up Open3D and added it to the quick install .exe already.
I'll send it to Joe for testing.

**Comment by fcr3** [comment]
> I tidied up Open3D and added it to the quick install .exe already.
> I'll send it to Joe for testing.

Cool! Thanks @adamchang2000

**Comment by adamchang2000** [comment]
So far, module works on main MSI development computer, MSI laptop, Intel-NUC, Joe's tablet

**Pull request merged**
